//
//  ResultsCode.h
//  halongIOSDemo
//
//  Created by 黄海明 on 15/5/7.
//  Copyright (c) 2015年 HL. All rights reserved.
//  //  15/7/15 更新于 OCR －by juein
//成功的


#define results801	@"登陆成功"
#define results802	@"已退出"
#define results803	@"已收藏"
#define results804	@"取消收藏"
#define results805	@"已点赞"
#define results806	@"取消点赞"
#define results807	@"已关注"
#define results808	@"取消关注"
#define results809	@"删除成功"
#define results810	@"增加成功"
#define results811	@"下单成功"
#define results812	@"发送成功"
#define results813	@"已留言"
#define results814	@"已反馈"
#define results815	@"已取消"
#define results816	@"暂无结果"
#define results817	@"上传成功"
#define results818	@"下载成功"
#define results819	@"修改成功"
#define results820	@"预定成功"
#define results821	@"发布成功"
#define results822	@"更新成功"
#define results823	@"注册成功"
#define results824	@"获取成功"
#define results825	@"发送成功"
#define results826	@"评论成功"
#define results827	@"已参加"
#define results828	@"参加成功"
#define results829	@"签到成功"
#define results830	@"已签到"
#define results831	@"举报成功"
#define results832	@"验证码正确"
#define results833	@"已是好友"
#define results834	@"加为好友"
#define results835	@"回复成功"





//失败的

#define results400 @"传入错误参数"
#define results401 @"尚未登录或会话超时"
#define results402 @"用户名不存在"
#define results403 @"密码错误"
#define results404 @"退出失败"
#define results405 @"服务器已关闭"
#define results406 @"暂无权限，请联系管理员"
#define results407 @"手机号码不正确"
#define results408 @"日期格式不正确"
#define results409 @"日期不能早于今天"
#define results410 @"日期不能晚于今天"
#define results411 @"用户名不能为空"
#define results412 @"用户名必须大于2并小于18个字符"
#define results413 @"密码不能为空"
#define results414 @"密码必须为字母或数字"
#define results415 @"密码必须大于6并小于20个字母或数字"
#define results416 @"确认密码不能为空"
#define results417 @"两次输入密码不一致"
#define results418 @"用户名已存在"
#define results419 @"有效期不能为空"
#define results420 @"旧密码不能为空"
#define results421 @"用户已不存在"
#define results422 @"已关注"
#define results423 @"旧密码不正确"
#define results424 @"主键ID冲突"
#define results425 @"请求超时"
#define results426 @"未传ID"
#define results427 @"邮件格式不正确"
#define results428 @"两次密码不对"
#define results429 @"非法操作"
#define results430 @"重复数据"
#define results431 @"重复操作"
#define results432 @"订单已存在"
#define results433 @"验证码错误"
#define results434 @"验证码不能为空"
#define results435 @"经度不能为空"
#define results436 @"纬度不能为空"
#define results437 @"签到失败"
#define results438 @"参加失败"
#define results439 @"举报失败"
#define results440 @"评论失败"
#define results441 @"不是创办人"
#define results442 @"发布失败"
#define results443 @"用户不存在"
#define results444 @"活动报名人数已满"
#define results445 @"加为好友失败"
#define results446 @"积分已用完"
#define results447 @"学校不能为空"
#define results448 @"年级不能为空"
#define results449 @"头像不能为空"
#define results450 @"身份不能为空"
#define results451 @"已回答15次，不能再回答"
#define results499 @"无效数据"

#define results500 @"已回答15次，不能再回答"


//mob 手机验证错误代码
#define results511 @"客户端请求不能被识别"
#define results512 @"服务器拒绝访问，或者拒绝操作"
#define results513 @"请求Appkey不存在或被禁用"
#define results514 @"无权执行该请求"
#define results515 @"服务器内部错误"
#define results516 @"服务器不支持客户端的请求"
#define results517 @"缺少必要的请求参数"
#define results518 @"请求中用户的手机号格式不正确"
#define results519 @"请求发送验证码次数超出限制"
#define results520 @"无效验证码"
#define results521 @"请求的令牌无效或者非法"
#define results522 @"请求的duid非法或者无效"
#define results523 @"请求验证的手机号码已经被验证"
#define results524 @"客户端请求发送短信验证过于频繁"
#define results525 @"需要签名检验"
#define results526 @"余额不足"
#define results0 @"验证码发送成功"

//验证码
#define resultssPhoneNumber @"手机号不能为空"
#define resultssCode @"验证码不能为空"
#define resultssPassword @"密码不能为空"

#define resultsThr @"失败"

